### ISSUE TITLE
Shodan API key Fails

### ISSUE THREAD

**Issue by ghost** [BullsEye0/shodan-eye#15]
Free Account level API fails when pasted into shodan-eye. Is this still working? (results in 'Error: Access Denied (403 Forbidden)')

**Comment by BullsEye0** [comment]
Yes, for sure Shodan Eye is still working. Sometimes it does. Don't know why. 
What I always recommend is making a new account on Shodan, and only using the new key.

**Comment by Wyvr3n** [comment]
_I just pasted my _api in the terminal and it says 403 failure

**Comment by jepunband** [comment]
yeah no longer works! API key fails

**Comment by g33k247** [comment]
Used my known good API key:

[~] Checking Shodan.io API Key... 
[✘] Error: Unable to connect to Shodan

Please advise soonest!

**Comment by BullsEye0** [comment]
The API KEY still wordks. I have seen many times that people should make another account with a different e-mail address to use Shodan and this script. 
So, it has nothing to do with Shodan Eye but with the correct API key.

**Comment by BullsEye0** [comment]
The API KEY still wordks. I have seen many times that people should make another account with a different e-mail address to use Shodan and this script.
So, it has nothing to do with Shodan Eye but with the correct API key.

**Comment by joeyfigaro** [comment]
Created new account, tried new API key associated with it. 403 is still an issue.

**Comment by joeyfigaro** [comment]
> The API KEY still wordks. I have seen many times that people should make another account with a different e-mail address to use Shodan and this script. So, it has nothing to do with Shodan Eye but with the correct API key.

Turns out you have to be a member–API keys are not valid unless you're a member. Membership currently requires a $5 payment.

They just don't do a good job of communicating this requirement at all.
