### ISSUE TITLE
SyntaxError: invalid syntax Random Choice

### ISSUE THREAD

**Issue by vanquishsecurity2** [BullsEye0/shodan-eye#4]
python -V = Python 3.7.5rc1 - Debian 9

Steps to reproduce:

-Get latest Github pull

sudo git clone https://github.com/BullsEye0/shodan-eye.git

-Install requirements

sudo pip install -r requirements.txt

-Run script:

sudo python shodan_eye.py

  File "shodan_eye.py", line 88
    print random.choice(choi)
               ^
SyntaxError: invalid syntax

**Comment by sundaysec** [comment]
Hello @vanquishsecurity2 
This error is brought up because shodaneye was built for python2 so for the meanwhile... use python2 to run shodaneye.
ie:
python2 shodan_eye.py
